#define MICROSTEPPING 16
// Stepper driver pins

#define XDRIVERDIRECTIONPIN 15
#define XDRIVERSTEPPIN 2

#define YDRIVERDIRECTIONPIN 21
#define YDRIVERSTEPPIN 22
#define YYDRIVERDIRECTIONPIN 19
#define YYDRIVERSTEPPIN 18

#define ZDRIVERDIRECTIONPIN 16
#define ZDRIVERSTEPPIN 4

#define TDRIVERDIRECTIONPIN 5
#define TDRIVERSTEPPIN 17

//Note: without microstepping
#define XSTEPPERMM 5
#define YSTEPPERMM 11.14
#define TSTEPPERDEG 0.41

#define MICROSTEPPING 16

#define XYMAXSPEED 500
#define ZMAXSPEED 800
#define TMAXSPEED 1200
#define XYMAXTRAVELSPEED 2000
#define ZMAXTRAVELSPEED 2000
#define TMAXTRAVELSPEED 2000


#define STEPPERACCELERATION 12000

