#define MICROSTEPPING 16
// Stepper driver pins

#define XDRIVERDIRECTIONPIN 15
#define XDRIVERSTEPPIN 2

#define YDRIVERDIRECTIONPIN 21
#define YDRIVERSTEPPIN 22
#define YYDRIVERDIRECTIONPIN 19
#define YYDRIVERSTEPPIN 18

#define ZDRIVERDIRECTIONPIN 16
#define ZDRIVERSTEPPIN 4

#define TDRIVERDIRECTIONPIN 5
#define TDRIVERSTEPPIN 17

//Note: without microstepping
#define XSTEPPERMM 5
#define YSTEPPERMM 9.90
#define ZSTEPPERMM 1
#define TSTEPPERDEG 0.41

#define MICROSTEPPING 16

#define XYMAXSPEED 1800
#define ZMAXSPEED 500
#define TMAXSPEED 1200
#define XYMAXTRAVELSPEED 2200
#define ZMAXTRAVELSPEED 2000
#define TMAXTRAVELSPEED 4000


#define STEPPERACCELERATION 12000
#define ZACCELERATION 2000


