#define MICROSTEPPING 16
// Stepper driver pins

//21 - 22 y
//19 - 18 y
//5 - 17 t
//16 - 4 z
//15 - 2 x
#define XDRIVERDIRECTIONPIN 15
#define XDRIVERSTEPPIN 2

#define YDRIVERDIRECTIONPIN 21
#define YDRIVERSTEPPIN 22
#define YYDRIVERDIRECTIONPIN 19
#define YYDRIVERSTEPPIN 18

#define ZDRIVERDIRECTIONPIN 5
#define ZDRIVERSTEPPIN 17

#define TDRIVERDIRECTIONPIN 4
#define TDRIVERSTEPPIN 16

//Node: without microstepping
#define XSTEPPERMM 5
#define YSTEPPERMM 11.14

#define MICROSTEPPING 16

#define MAXSTEPPERSPEED 8000
#define STEPPERACCELERATION 12000

